services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      SA_PASSWORD: "${SA_PASSWORD:?errSA}"
      ACCEPT_EULA: "Y"
      TEST_POPULATE: "${TEST_POPULATE:?false}" # Fill the tables with sample data.
      RESET_DB: "${RESET_DB:?false}" # Clean up everything that was in the database before, reapply the DDL file
    ports:
      - "1433:1433"
    volumes:
      - ./database:/database
    entrypoint: ["/bin/bash", "/database/entrypoint.sh"]
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P $SA_PASSWORD -C -No -Q 'SELECT 1' || exit 1" ]
      interval: 20s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_backend
    environment:
      - DATABASE_URL=f"mssql+pyodbc://vertex:{Settings.SA_PASSWORD}@sqlserver2022.database.windows.net:1433/BookXchange?driver=ODBC+Driver+18+for+SQL+Server&Encrypt=yes&TrustServerCertificate=no&Connection+Timeout=30"
      
    ports:
      - "8000:8000"
    volumes:
      - ..:/app
    working_dir: /app
    depends_on:
      sqlserver:
        condition: service_healthy
    #command: [ "sh", "-c", "sleep infinity" ]
    command: ["uvicorn", "backend.main:app", "--port", "8000", "--host", "0.0.0.0"]

